name: vright_brothers_sciml
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipykernel
  - pip
  - pip:
    - h5py
    - tqdm
